routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Route::resource('/', 'ServicesController@index');

Route::resource('/beautyroom', 'ServicesController');
Auth::routes();


// Route::get('/', function(){
// 	return redirect()->route('beautyroom.index');
// });
Route::get('/home', 'ServicesController@index');


Route::get('/contacts', 'ContactController@index');

Route::resource('/user', 'UserController');

Route::resource('/upload', 'UploadController@upload');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware(function($request, $next){
           if(\Auth::guest() || (!\Auth::guest() && \Auth::user()->is_admin == 0)){
                return redirect()->route('login');
            }
            return $next($request);
        });
            
    }

    public function index()
    {
        $users = \App\User::all();

        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_user = \App\User::create($request->all());
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\User::find($id);

        return view('user.create', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \App\User::find($id)->update($request->all());

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\User::find($id)->delete();

        return redirect()->route('user.index');
    }
}

resources/views/user/create.blade.php
@extends("layouts.main")

@section("content")
<div class="container">
	@if(isset($user))
		<form method="POST" action="{{ route('user.update', $user->id) }}">
		<input type="hidden" name="_method" value="PUT">
	@else
		<form method="POST" action="{{ route('user.store') }}">
	@endif



		{{ csrf_field() }}

		<label>Name: </label>
		@if(isset($user))
			<input value="{{ $user['name'] }}" class="form-control" type="text" name="name">
		@else
			<input class="form-control" type="text" name="name">
		@endif

		<label>Email: </label>
		@if(isset($user))
			<input value="{{ $user['email'] }}" class="form-control" type="text" name="email" >
		@else
			<input class="form-control" type="text" name="email" >
		@endif

		@if(isset($user))
			<button class="btn btn-primary">Update user</button>
		@else
			<button class="btn btn-primary">Add user</button>
		@endif

		@if($user->is_admin = 1)
			<input type="hidden" checked name="is_admin" value="0">
			<input type="checkbox" checked name="is_admin" value="1">Make this user Admin
		@else
		@endif
	</form>


</div>
@endsection    

resources/views/user/index.blade.php
@extends('layouts.main')

@section('content')
	<div class="container">
		<h3>Users List</h3> <br>
		<div class="row">
			<table class="col-md-12" width="100%">
				<tbody>
					<tr>
				    	<th>User Name</th>
				    	<th>User E-Mail</th>
				    	<th>Edit User</th>
				    	<th>Delete User</th>
			    	</tr>

				   	@foreach($users as $user)
			    		<tr>
				    		<td>{{ $user->name}}</td>
				    		<td>{{ $user->email }}</td>
				    		<td> 
					    		<a class="btn btn-primary" href="{{ route('user.edit', $user->id) }}">EDIT</a>
				    		</td>

				    		<td>
								<form method="POST" action="{{ route('user.destroy', $user->id) }}">
									<input type="hidden" name="_method" value="DELETE">
									{{ csrf_field() }}
									<button class="btn btn-danger">DELETE</button>
								</form>
							</td>
			    		</tr>
					@endforeach
				</tbody>
			</table>
		</div><!-- row -->
	</div>
@endsection