routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


Route::resource('/', 'ServicesController@index');

Route::resource('/beautyroom', 'ServicesController');
Auth::routes();


// Route::get('/', function(){
// 	return redirect()->route('beautyroom.index');
// });
Route::get('/home', 'ServicesController@index');


Route::get('/contacts', 'ContactController@index');

Route::resource('/user', 'UserController');

Route::resource('/upload', 'UploadController@upload');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/layouts/create.blade.php
@extends("layouts.main")

@section("content")

<!-- 	<h3>{{ isset($service) ? 'Edit service' : 'Add service' }}</h3>

	<form action="{{ route('beautyroom.store') }}" method="POST"> -->

<!-- <div id="forma">
    {{ Form::open(['url' => '/formos', 'method' => "POST", 'class' => 'labai-gera-forma']) }}
    {{ Form::text('name', 'this is name', ['class' => 'awesome', 'id'=>"geras"]) }}
    {{ Form::text('email', 'example@gmail.com', ['class' => 'awesome', 'id'=>"geras1"]) }}
    {{ Form::text('email-confirm', 'example@gmail.com', ['class' => 'awesome', 'id'=>"geras1"]) }}
    {{ Form::submit('Click Me!') }}
    {{ Form::close() }}
</div> -->

		 @if(isset($service))
			<form method="POST" action="{{ route('beautyroom.update', $service->id) }}">
			<input type="hidden" name="_method" value="PUT">
		@else
			<form method="POST" action="{{ route('beautyroom.store') }}">
		@endif

	<div class="container">
		@if(isset($service))
			<form method="POST" action="{{ route('beautyroom.update', $service->id) }}">
			<input type="hidden" name="_method" value="PUT">
		@else
			<form method="POST" action="{{ route('beautyroom.store') }}">
		@endif

		{{ csrf_field() }}

			<label>Title: </label>
			@if(isset($service))
				<input value="{{ $service['title'] }}" class="form-control" type="text" name="title">
			@else
				<input class="form-control" type="text" name="title">
			@endif


			<label>Price: </label>
			@if(isset($service))
				<input value="{{ $service['price'] }}" class="form-control" type="text" name="price" >
			@else
				<input class="form-control" type="text" name="price" >
			@endif

			<label>Image: </label>
			@if(isset($service))
				<input value="{{ $service['image'] }}" class="form-control" type="text" name="image" >
			@else
				<input class="form-control" type="text" name="image" >
			@endif



			<label>Description: </label>
			@if(isset($service))
				<textarea class="form-control" name="description" cols="30" rows="10" >{{ $service['description'] }}</textarea>
			@else
				<textarea class="form-control" name="description" cols="30" rows="10"></textarea>
			@endif

			<button class="btn btn-primary">Save</button>
			<!-- <input class="btn btn-primary" type="submit" name="save"> -->
		</form>
	</div>
@endsection

resources/views/layouts/footer.blade.php
	<footer class="footer">
		<div class="container">

			<p>Lorem Ipsum</p>

			<p>
				Rutrum maecenas eget amet ante, fusce consectetuer et vel eu sollicitudin, urna sapien non quam. Vel orci maecenas amet.
			</p>

			<p>
				Rutrum maecenas eget amet ante, fusce consectetuer et vel eu sollicitudin, urna sapien non.
			</p>

			<nav>
				<ul class="logo-nav">	
					<li><a href="{{ route('beautyroom.index') }}">Home</a></li>
					<li><a href="#aboutUs-block">About Us</a></li>
					<li><a href="{{ URL::to('contacts') }}">Contacts</a></li>
				</ul>
			</nav>

			<p>
				2016 - 3WA - The Beauty Room
			</p>
			<small>Eimantas Cereska</small>
		</div>
		
		<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	</footer>
		</body>	
	</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- <link rel="stylesheet" type="text/css" href="css/main.css"> -->
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="flexslider.css" type="text/css" media="screen" />
	<link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}"> 
	<link rel="stylesheet" type="text/css" href="{{ asset('css/flexslider.css') }}">
	<!-- <script type="text/javascript" src="{{ URL::asset('js/jquery.js') }}"></script> -->
	<title>Beauty salon page</title>
</head>
<body>
	<header>
		<div class="header-content">
			<div class="container">			
				<div class="row">	
					<div class="col-xs-6 col-md-6">
						<p><a href="{{ route('beautyroom.index') }}">www.beauty.com</a></p>
					</div>

					<div class="col-xs-6 col-md-6">
						@if (Auth::guest())
                            <div class="login-buttons"><a href="{{ url('login') }}">Staff Login</a></div>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
					</div>
				</div> <!-- row -->
			</div> <!-- container -->
		</div> <!-- header-content -->
	
		<div class="container">
			<div class="logo-nav">
				<div class="row">
					<div class="col-xs-12 col-md-6 logo"> <!-- col-xs-12 col-md-6 -->
						<a href="{{ route('beautyroom.index') }}"><img src="http://localhost/project1/img/logo1.png"></a>
					</div>

					<div class="col-xs-12 col-md-6 navi"> <!--  -->
						<ul>	
							<li><a href="{{ route('beautyroom.index') }}">Home</a></li>
							<li><a href="#aboutUs-block">About Us</a></li>
							<li><a href="{{ URL::to('contacts') }}">Contacts</a></li>
						</ul>
					</div>
				</div> <!-- row -->
			</div> <!-- logo-nav -->
		</div> <!-- container -->
	</header>

resources/views/layouts/index.blade.php
@extends("layouts.main")

@section("content")

<div class="container">
    <div class="border-slider"> 
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div id="main" role="main">
                    <section class="slider">
                        <div class="flexslider">
                            <ul class="slides">
                                <li><img class="img-responsive" src="http://localhost/project1/img/makeup.jpg"/></li>
                                <li><img class="img-responsive" src="http://localhost/project1/img/hairmodeling2.jpg"/></li>
                                <li><img class="img-responsive" src="http://localhost/project1/img/nails.jpg"/></li>
                                <li><img class="img-responsive" src="http://localhost/project1/img/asd.jpg"/></li>
                            </ul> <!-- slides -->

                        </div> <!-- flexslider -->
                    </section> <!-- slider -->
                </div> <!-- main -->

                <!-- jQuery -->
                <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
                <script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>

                <!-- FlexSlider -->
                <script defer src="{{ asset('js/jquery.flexslider.js') }}"></script>

                <script type="text/javascript">
                    $(window).load(function(){
                        $('.flexslider').flexslider({
                            animation: "slide",
                            start: function(slider){
                                $('body').removeClass('loading');
                            }
                        });
                    });
                </script>
            </div>
        </div> <!-- row -->
    </div> <!-- border-slider -->
   

        @if (!Auth::guest() && Auth::user()->is_admin)       
            <a class="btn btn-default add-users-buttons" href="{{ route('beautyroom.create') }}">Add New Service</a>
            <a class="btn btn-default add-users-buttons" href="{{ route('user.index') }}">Users List</a>
        @else
        @endif
 


    <div class="services">
        <h6>Offers</h6>
        <div class="row">
            @foreach($services as $service)
               <div class="col-xs-12 col-md-3">
                    <div class="services-content service1">
                        <h2>{{ $service->title }}</h2>
                        <h5>{{ $service->price }}€</h5>
                        <a href="{{ route('beautyroom.show', $service->id) }}"><img src="{{ $service->image }}"></a>
                        
                        @if (!Auth::guest() && Auth::user()->is_admin)
                            <div class="row">
                                <div class="col-md-6 admin-buttons">
                                    <a class="btn btn-default" href="{{ route('beautyroom.edit', $service->id) }}">EDIT</a>
                                </div>

                                <div class="col-md-6 admin-buttons">
                                    <form method="POST" action="{{ route('beautyroom.destroy', $service->id) }}">
                                        <input type="hidden" name="_method" value="DELETE">
                                        {{ csrf_field() }}
                                        <button class="btn btn-danger">DELETE</button>
                                    </form>
                                </div>
                            </div>
                        @else
                        @endif

                    </div>
                </div> 
            @endforeach
        </div> <!-- row -->
        
    </div> <!-- services -->

    <blockquote class="col-xs-12 col-sm-12 col-md-12 quote">
        <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
        <footer class="pull-right">Wikipedia</footer>
    </blockquote>

    <div class="details">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <h3 id="aboutUs-block">About Us</h3>
                <p>At Beauty Room, our quality trained Beauty Therapists consistently provide our clients with a high standard of customer service and skill.
                With one convenient location in the heart of Kaunas City, you can be sure to step out of the hustle and bustle and into our laid-back, relaxed and friendly environment.
                Escape to our fun & friendly environment where our fully qualified beauty therapists provide the highest standards, across our wide range of treatments.
                Seeking a quick wax on your lunch break, a wonderful make-up for your evening or another manicure and/or pedicure? We can cater for all your beauty needs.</p>
            </div>

        </div> <!-- row -->
    </div> <!-- details -->
</div> <!-- container -->

@endsection

resources/views/layouts/main.blade.php
@include("layouts.header")

    @yield("content")

@include("layouts.footer")

resources/views/layouts/show.blade.php
@extends("layouts.main")

@section("content")
	<div class="container">
		<div class="row">
			<div class="row">
				<div class="col-md-12">
					<h1>{{ $service->title }}</h1>
	            	<h2>{{ $service->price }} €</h2>
				</div>	
            </div>
            
            <div class="col-xs-12 col-md-6">
                <img class="img-responsive showblade-img" src="{{ $service->image }}">
            </div> 

           <div class="col-xs-12 col-md-6">
                <p>{{ $service->description }}</p>
            </div> 
		</div> <!-- row -->
	</div> <!-- container -->
@endsection